## Creating NumPy ndArrays
Mainly there are two ways to create NumPy ndArrays:
1. Using array() function to create ndArrays from Python lists, tuples, or any other iterable object.
2. Using built-in functions to create ndArrays, such as arange(), ones(), zeros(), etc.

In [1]:
import numpy as np

x = np.array([1, 2, 3])

In [2]:
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int64')

In [4]:
x.shape

(3,)

In [5]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
Y.shape

(3, 3)

In [7]:
Y.size

9

In [8]:
x = np.array(["Hello", "World"])
print(x)

['Hello' 'World']


In [9]:
print("shape: ", x.shape)
print("type: ", type(x))
print("dtype: ", x.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


### Upcasting
NumPy makes sure that all the elements in a NumPy array are of the same data type. If the elements are of different data types, NumPy will upcast if possible. The order of upcasting is: bool -> int -> float -> str.

In [10]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [11]:
x = np.array([1.5, 2.2, 3.2], dtype=np.int64)
print(x, x.dtype)

[1 2 3] int64


In [12]:
x = np.array([1, 2, 3])
np.save('my_array', x)

In [13]:
y = np.load('my_array.npy')
print(y)

[1 2 3]


#### Creating ndArrays from built-in functions

In [14]:
X = np.zeros((3, 4), dtype=np.int32)
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
X = np.ones((3, 4))
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
X = np.full((3, 4), 5)
print(X)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Identity Matrix

In [17]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Diagonal Matrix

In [18]:
X = np.diag([10, 1, 3, 5])
print(X)

[[10  0  0  0]
 [ 0  1  0  0]
 [ 0  0  3  0]
 [ 0  0  0  5]]


In [19]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
x = np.arange(5, 10)
print(x)

[5 6 7 8 9]


In [21]:
x = np.arange(2, 12, 2)
print(x)

[ 2  4  6  8 10]


In [22]:
x = np.linspace(0, 20, 10, endpoint=False)
print(x)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [23]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [25]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [26]:
Y = np.arange(20).reshape(4, 5)
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [28]:
X = np.random.random((5, 3))
print(X)

[[0.24117899 0.60286121 0.6475844 ]
 [0.75101848 0.31694875 0.8289811 ]
 [0.98211589 0.55440586 0.71955096]
 [0.32675047 0.04261058 0.01047878]
 [0.51175323 0.31330565 0.07248595]]


In [29]:
X = np.random.randint(2, 10, (3, 3))
print(X)

[[2 3 2]
 [7 2 6]
 [6 8 6]]


In [30]:
X = np.random.normal(0, 0.3, (100, 100))
print(X)

[[-0.13038395  0.08309886 -0.38772676 ...  0.29373515 -0.71588397
   0.13406396]
 [ 0.04968335 -0.36753022  0.14054336 ...  0.29909537  1.00927666
   0.4684699 ]
 [ 0.30134732  0.00892746  0.08523548 ...  0.06723597 -0.34980884
   0.22236839]
 ...
 [-0.03974024  0.32875631  0.0280971  ...  0.08341099 -0.1095732
   0.12710488]
 [ 0.02162086  0.05865158  0.20892646 ... -0.01412962 -0.40046711
  -0.20034597]
 [ 0.38078983  0.18180625 -0.38322426 ... -0.35092546  0.06130935
   0.29424101]]


In [31]:
print("Mean: ", X.mean())
print("Std: ", X.std())
print("Max: ", X.max())
print("Min: ", X.min())
print("# positive: ", (X > 0).sum())
print("# negative: ", (X < 0).sum())

Mean:  0.00034522778367641015
Std:  0.3003529139959287
Max:  1.1098592665196823
Min:  -1.2171808188267552
# positive:  4976
# negative:  5024


## Accessing, Deleting and Inserting Elements Into ndArrays

In [32]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [33]:
print("1st element: ", x[0])
print("2nd element: ", x[1])
print("5th element: ", x[4])

1st element:  1
2nd element:  2
5th element:  5


In [34]:
print("1st element: ", x[-5])
print("2nd element: ", x[-4])
print("5th element: ", x[-1])

1st element:  1
2nd element:  2
5th element:  5


In [35]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [36]:
X = np.arange(1, 10).reshape(3, 3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print("Element (0, 0): ", X[0, 0])
print("Element (0, 1): ", X[0, 1])
print("Element (2, 2): ", X[2, 2])

Element (0, 0):  1
Element (0, 1):  2
Element (2, 2):  9


In [38]:
X[0, 0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [39]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0, 4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [40]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

W = np.delete(Y, 0, axis=0)
print('\n',W)

V = np.delete(Y, [0, 2], axis=1)
print('\n',V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [41]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [42]:
x = np.append(x, [7, 8])
print(x)

[1 2 3 4 5 6 7 8]


In [43]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
W = np.append(Y, [[10, 11, 12]], axis=0)
print('\n',W)


 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
V = np.append(Y, [[10], [11], [12]], axis=1)
print('\n',V)


 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [46]:
x = np.array([1, 2, 5, 6, 7])
print(x)

[1 2 5 6 7]


In [47]:
x = np.insert(x, 2, [3, 4])
print(x)

[1 2 3 4 5 6 7]


In [48]:
Y = np.array([[1, 2, 3], [7, 8, 9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [49]:
W = np.insert(Y, 1, [4, 5, 6], axis=0)
print('\n',W)


 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
V = np.insert(Y, 1, 5, axis=1)
print('\n',V)


 [[1 5 2 3]
 [7 5 8 9]]


In [51]:
x = np.array([1, 2])
print(x)

[1 2]


In [52]:
Y = np.array([[3, 4], [5, 6]])
print(Y)

[[3 4]
 [5 6]]


In [53]:
z = np.vstack((x, Y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [55]:
w = np.hstack((Y, x.reshape(2, 1)))
print(w)

[[3 4 1]
 [5 6 2]]
