## Creating NumPy ndArrays
Mainly there are two ways to create NumPy ndArrays:
1. Using array() function to create ndArrays from Python lists, tuples, or any other iterable object.
2. Using built-in functions to create ndArrays, such as arange(), ones(), zeros(), etc.

In [1]:
import numpy as np

x = np.array([1, 2, 3])

In [2]:
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int64')

In [4]:
x.shape

(3,)

In [5]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
Y.shape

(3, 3)

In [7]:
Y.size

9

In [8]:
x = np.array(["Hello", "World"])
print(x)

['Hello' 'World']


In [9]:
print("shape: ", x.shape)
print("type: ", type(x))
print("dtype: ", x.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


### Upcasting
NumPy makes sure that all the elements in a NumPy array are of the same data type. If the elements are of different data types, NumPy will upcast if possible. The order of upcasting is: bool -> int -> float -> str.

In [10]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [11]:
x = np.array([1.5, 2.2, 3.2], dtype=np.int64)
print(x, x.dtype)

[1 2 3] int64


In [12]:
x = np.array([1, 2, 3])
np.save('my_array', x)

In [13]:
y = np.load('my_array.npy')
print(y)

[1 2 3]


#### Creating ndArrays from built-in functions

In [14]:
X = np.zeros((3, 4), dtype=np.int32)
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
X = np.ones((3, 4))
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
X = np.full((3, 4), 5)
print(X)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Identity Matrix

In [17]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Diagonal Matrix

In [18]:
X = np.diag([10, 1, 3, 5])
print(X)

[[10  0  0  0]
 [ 0  1  0  0]
 [ 0  0  3  0]
 [ 0  0  0  5]]


In [19]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
x = np.arange(5, 10)
print(x)

[5 6 7 8 9]


In [21]:
x = np.arange(2, 12, 2)
print(x)

[ 2  4  6  8 10]


In [22]:
x = np.linspace(0, 20, 10, endpoint=False)
print(x)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [23]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [25]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [26]:
Y = np.arange(20).reshape(4, 5)
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [28]:
X = np.random.random((5, 3))
print(X)

[[0.13663164 0.14627096 0.44243061]
 [0.33834062 0.52522694 0.11084157]
 [0.39888228 0.35962077 0.52269727]
 [0.16298292 0.23566251 0.48382546]
 [0.89015749 0.68255877 0.31410635]]


In [29]:
X = np.random.randint(2, 10, (3, 3))
print(X)

[[3 2 8]
 [6 3 9]
 [4 7 8]]


In [30]:
X = np.random.normal(0, 0.3, (100, 100))
print(X)

[[ 0.21851856 -0.20360027 -0.53638301 ... -0.18711411 -0.24633768
  -0.46136849]
 [-0.34870134 -0.04608555  0.08423844 ... -0.30356361 -0.31162165
   0.31528861]
 [-0.64042626 -0.70561999  0.46538414 ...  0.13093705  0.09371683
   0.11726124]
 ...
 [ 0.13691932 -0.08157684 -0.0091071  ... -0.3359852  -0.42138582
   0.2177096 ]
 [-0.13274586  0.43225208  0.32818676 ...  0.31567877 -0.55286656
   0.37620729]
 [-0.22655606 -0.23330367  0.23897659 ... -0.10119659  0.0183448
   0.13926074]]


In [31]:
print("Mean: ", X.mean())
print("Std: ", X.std())
print("Max: ", X.max())
print("Min: ", X.min())
print("# positive: ", (X > 0).sum())
print("# negative: ", (X < 0).sum())

Mean:  -0.0029138484402194344
Std:  0.3018992881060093
Max:  1.2295049302044299
Min:  -1.1036633996666543
# positive:  4964
# negative:  5036


## Accessing, Deleting and Inserting Elements Into ndArrays

In [32]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [33]:
print("1st element: ", x[0])
print("2nd element: ", x[1])
print("5th element: ", x[4])

1st element:  1
2nd element:  2
5th element:  5


In [34]:
print("1st element: ", x[-5])
print("2nd element: ", x[-4])
print("5th element: ", x[-1])

1st element:  1
2nd element:  2
5th element:  5


In [35]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [36]:
X = np.arange(1, 10).reshape(3, 3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print("Element (0, 0): ", X[0, 0])
print("Element (0, 1): ", X[0, 1])
print("Element (2, 2): ", X[2, 2])

Element (0, 0):  1
Element (0, 1):  2
Element (2, 2):  9


In [38]:
X[0, 0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [39]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0, 4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [40]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

W = np.delete(Y, 0, axis=0)
print('\n',W)

V = np.delete(Y, [0, 2], axis=1)
print('\n',V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [41]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [42]:
x = np.append(x, [7, 8])
print(x)

[1 2 3 4 5 6 7 8]


In [43]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
W = np.append(Y, [[10, 11, 12]], axis=0)
print('\n',W)


 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
V = np.append(Y, [[10], [11], [12]], axis=1)
print('\n',V)


 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [46]:
x = np.array([1, 2, 5, 6, 7])
print(x)

[1 2 5 6 7]


In [47]:
x = np.insert(x, 2, [3, 4])
print(x)

[1 2 3 4 5 6 7]


In [48]:
Y = np.array([[1, 2, 3], [7, 8, 9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [49]:
W = np.insert(Y, 1, [4, 5, 6], axis=0)
print('\n',W)


 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
V = np.insert(Y, 1, 5, axis=1)
print('\n',V)


 [[1 5 2 3]
 [7 5 8 9]]


In [51]:
x = np.array([1, 2])
print(x)

[1 2]


In [52]:
Y = np.array([[3, 4], [5, 6]])
print(Y)

[[3 4]
 [5 6]]


In [53]:
z = np.vstack((x, Y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [54]:
w = np.hstack((Y, x.reshape(2, 1)))
print(w)

[[3 4 1]
 [5 6 2]]


## Slicing ndArrays

In [55]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [56]:
z = X[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [57]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [58]:
z = X[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [59]:
z = X[:, 2]
print(z)

[ 3  8 13 18]


In [60]:
z = X[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [61]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [62]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [63]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [64]:
print(X)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [65]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [66]:
z = np.copy(X[1:, 2:])
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [67]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [68]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [69]:
z = np.diag(X)
print(z)

[ 1  7 13 19]


In [70]:
z = np.diag(X, k=1)
print(z)

[ 2  8 14 20]


In [71]:
z = np.diag(X, k=-1)
print(z)

[ 6 12 18]


In [72]:
X = np.array([[1, 3, 5], [1, 5, 2], [3, 4, 2]])
z = np.unique(X)
print(z)

[1 2 3 4 5]


## Boolean indexing, Set Operations, and Sorting

## 

In [73]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [74]:
print(X[X > 10])


[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [75]:
print(X[X <= 7])


[0 1 2 3 4 5 6 7]


In [76]:
print(X[(X > 10) & (X < 17)])

[11 12 13 14 15 16]


In [77]:
X[(X > 10) & (X < 17)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [78]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [79]:
x = np.random.randint(1, 11, size=(10,))
print(x)

[ 6  6 10 10 10  8  7  7  1  3]


In [80]:
print(np.sort(x))
print(x)

[ 1  3  6  6  7  7  8 10 10 10]
[ 6  6 10 10 10  8  7  7  1  3]


In [81]:
x.sort()
print(x)

[ 1  3  6  6  7  7  8 10 10 10]


In [82]:
X = np.random.randint(1, 11, size=(5, 5))
print(X)

[[ 6  6 10  4  6]
 [ 2  6  9  4  2]
 [ 2  5  1  5  2]
 [ 7  5  4 10  4]
 [ 2 10  1  7  2]]


In [83]:
print(np.sort(X, axis=0))

[[ 2  5  1  4  2]
 [ 2  5  1  4  2]
 [ 2  6  4  5  2]
 [ 6  6  9  7  4]
 [ 7 10 10 10  6]]


In [84]:
print(np.sort(X, axis=1))

[[ 4  6  6  6 10]
 [ 2  2  4  6  9]
 [ 1  2  2  5  5]
 [ 4  4  5  7 10]
 [ 1  2  2  7 10]]


### Arithematic Operations and Broadcasting


In [85]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])
print(x)
print(y)

[1 2 3 4 5]
[6 7 2 8 4]


In [86]:
print(x + y)
print(np.add(x, y))

[ 7  9  5 12  9]
[ 7  9  5 12  9]


In [87]:
print(x - y)
print(np.subtract(x, y))

[-5 -5  1 -4  1]
[-5 -5  1 -4  1]


In [88]:
print(x * y)
print(np.multiply(x, y))

[ 6 14  6 32 20]
[ 6 14  6 32 20]


In [89]:
print(x / y)
print(np.divide(x, y))

[0.16666667 0.28571429 1.5        0.5        1.25      ]
[0.16666667 0.28571429 1.5        0.5        1.25      ]


In [90]:
X = np.array([1, 2, 3, 4]).reshape(2, 2)
Y = np.array([6, 7, 8, 9]).reshape(2, 2)
print(X)
print(Y)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


In [91]:
print(X + Y)
print(np.add(X, Y))


[[ 7  9]
 [11 13]]
[[ 7  9]
 [11 13]]


In [92]:
print(X - Y)
print(np.subtract(X, Y))

[[-5 -5]
 [-5 -5]]
[[-5 -5]
 [-5 -5]]


In [93]:
print(X * Y)
print(np.multiply(X, Y))

[[ 6 14]
 [24 36]]
[[ 6 14]
 [24 36]]


In [94]:
print(X / Y)
print(np.divide(X, Y))

[[0.16666667 0.28571429]
 [0.375      0.44444444]]
[[0.16666667 0.28571429]
 [0.375      0.44444444]]


In [98]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [99]:
print(np.exp(x))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [100]:
print(np.power(x, 2))

[ 1  4  9 16 25]


In [102]:
print('Average for X: ', X.mean())

Average for x:  2.5


In [103]:
print("Average of columns: ", X.mean(axis=0))
print("Average of rows: ", X.mean(axis=1))

Average of columns:  [2. 3.]
Average of rows:  [1.5 3.5]


In [104]:
print("Sum of all elements: ", X.sum())
print("Sum of columns: ", X.sum(axis=0))
print("Sum of rows: ", X.sum(axis=1))

Sum of all elements:  10
Sum of columns:  [4 6]
Sum of rows:  [3 7]


In [105]:
X.std()

1.118033988749895

In [106]:
np.median(X)

2.5

In [107]:
X.max()

4

In [108]:
X.min()

1

In [109]:
print(3 + X)

[[4 5]
 [6 7]]


In [110]:
print(3 - X)

[[ 2  1]
 [ 0 -1]]


In [111]:
print(X * 3)

[[ 3  6]
 [ 9 12]]


In [112]:
print(X / 3)

[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [113]:
Y = np.arange(9).reshape(3, 3)
print(Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [114]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [115]:
print(x + Y)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [121]:
z = np.arange(3).reshape(3, 1)
print(z)

[[0]
 [1]
 [2]]


In [122]:
print(Y + z)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
