## Creating NumPy ndArrays
Mainly there are two ways to create NumPy ndArrays:
1. Using array() function to create ndArrays from Python lists, tuples, or any other iterable object.
2. Using built-in functions to create ndArrays, such as arange(), ones(), zeros(), etc.

In [56]:
import numpy as np

x = np.array([1, 2, 3])

In [57]:
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [58]:
x.dtype

dtype('int64')

In [59]:
x.shape

(3,)

In [60]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
Y.shape

(3, 3)

In [62]:
Y.size

9

In [63]:
x = np.array(["Hello", "World"])
print(x)

['Hello' 'World']


In [64]:
print("shape: ", x.shape)
print("type: ", type(x))
print("dtype: ", x.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


### Upcasting
NumPy makes sure that all the elements in a NumPy array are of the same data type. If the elements are of different data types, NumPy will upcast if possible. The order of upcasting is: bool -> int -> float -> str.

In [65]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [66]:
x = np.array([1.5, 2.2, 3.2], dtype=np.int64)
print(x, x.dtype)

[1 2 3] int64


In [67]:
x = np.array([1, 2, 3])
np.save('my_array', x)

In [68]:
y = np.load('my_array.npy')
print(y)

[1 2 3]


#### Creating ndArrays from built-in functions

In [69]:
X = np.zeros((3, 4), dtype=np.int32)
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [70]:
X = np.ones((3, 4))
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [71]:
X = np.full((3, 4), 5)
print(X)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Identity Matrix

In [72]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Diagonal Matrix

In [73]:
X = np.diag([10, 1, 3, 5])
print(X)

[[10  0  0  0]
 [ 0  1  0  0]
 [ 0  0  3  0]
 [ 0  0  0  5]]


In [74]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [75]:
x = np.arange(5, 10)
print(x)

[5 6 7 8 9]


In [76]:
x = np.arange(2, 12, 2)
print(x)

[ 2  4  6  8 10]


In [77]:
x = np.linspace(0, 20, 10, endpoint=False)
print(x)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [78]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [79]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [80]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [81]:
Y = np.arange(20).reshape(4, 5)
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [82]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [83]:
X = np.random.random((5, 3))
print(X)

[[0.82825626 0.42574165 0.32547253]
 [0.74342001 0.84791078 0.13612156]
 [0.38117897 0.04947155 0.09281928]
 [0.48931328 0.94546564 0.03612315]
 [0.75024257 0.03383713 0.69923207]]


In [84]:
X = np.random.randint(2, 10, (3, 3))
print(X)

[[2 6 2]
 [6 2 9]
 [5 9 3]]


In [85]:
X = np.random.normal(0, 0.3, (100, 100))
print(X)

[[-0.25476411  0.08188759 -0.42554237 ... -0.13134744  0.41924057
   0.50466127]
 [-0.67707747 -0.51577156 -0.28675606 ... -0.01081424  0.18032157
   0.1039274 ]
 [ 0.10117642  0.2522093   0.52588071 ...  0.22324059 -0.05684355
   0.07948086]
 ...
 [-0.00881036 -0.47353962  0.07446379 ... -0.54381489 -0.18286649
   0.2283656 ]
 [ 0.22173338 -0.27601497 -0.27650248 ...  0.32371027  0.01447646
   0.16647048]
 [-0.22206154  0.15961622 -0.0588759  ... -0.27284758  0.94087129
   0.16276669]]


In [86]:
print("Mean: ", X.mean())
print("Std: ", X.std())
print("Max: ", X.max())
print("Min: ", X.min())
print("# positive: ", (X > 0).sum())
print("# negative: ", (X < 0).sum())

Mean:  -0.0004584415724337138
Std:  0.3021444141940824
Max:  1.1163293302926425
Min:  -1.1239358770451195
# positive:  4975
# negative:  5025


## Accessing, Deleting and Inserting Elements Into ndArrays

In [87]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [88]:
print("1st element: ", x[0])
print("2nd element: ", x[1])
print("5th element: ", x[4])

1st element:  1
2nd element:  2
5th element:  5


In [89]:
print("1st element: ", x[-5])
print("2nd element: ", x[-4])
print("5th element: ", x[-1])

1st element:  1
2nd element:  2
5th element:  5


In [90]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [91]:
X = np.arange(1, 10).reshape(3, 3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [92]:
print("Element (0, 0): ", X[0, 0])
print("Element (0, 1): ", X[0, 1])
print("Element (2, 2): ", X[2, 2])

Element (0, 0):  1
Element (0, 1):  2
Element (2, 2):  9


In [93]:
X[0, 0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [94]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0, 4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [95]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

W = np.delete(Y, 0, axis=0)
print('\n',W)

V = np.delete(Y, [0, 2], axis=1)
print('\n',V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [96]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [97]:
x = np.append(x, [7, 8])
print(x)

[1 2 3 4 5 6 7 8]


In [98]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [99]:
W = np.append(Y, [[10, 11, 12]], axis=0)
print('\n',W)


 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [100]:
V = np.append(Y, [[10], [11], [12]], axis=1)
print('\n',V)


 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [101]:
x = np.array([1, 2, 5, 6, 7])
print(x)

[1 2 5 6 7]


In [102]:
x = np.insert(x, 2, [3, 4])
print(x)

[1 2 3 4 5 6 7]


In [103]:
Y = np.array([[1, 2, 3], [7, 8, 9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [104]:
W = np.insert(Y, 1, [4, 5, 6], axis=0)
print('\n',W)


 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [105]:
V = np.insert(Y, 1, 5, axis=1)
print('\n',V)


 [[1 5 2 3]
 [7 5 8 9]]


In [106]:
x = np.array([1, 2])
print(x)

[1 2]


In [107]:
Y = np.array([[3, 4], [5, 6]])
print(Y)

[[3 4]
 [5 6]]


In [108]:
z = np.vstack((x, Y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
w = np.hstack((Y, x.reshape(2, 1)))
print(w)

[[3 4 1]
 [5 6 2]]


## Slicing ndArrays

In [110]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [112]:
z = X[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [113]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [115]:
z = X[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [116]:
z = X[:, 2]
print(z)

[ 3  8 13 18]


In [117]:
z = X[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [120]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [121]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [122]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [123]:
print(X)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [124]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [126]:
z = np.copy(X[1:, 2:])
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [127]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [128]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [129]:
z = np.diag(X)
print(z)

[ 1  7 13 19]


In [130]:
z = np.diag(X, k=1)
print(z)

[ 2  8 14 20]


In [131]:
z = np.diag(X, k=-1)
print(z)

[ 6 12 18]


In [132]:
X = np.array([[1, 3, 5], [1, 5, 2], [3, 4, 2]])
z = np.unique(X)
print(z)

[1 2 3 4 5]


## 