## Creating NumPy ndArrays
Mainly there are two ways to create NumPy ndArrays:
1. Using array() function to create ndArrays from Python lists, tuples, or any other iterable object.
2. Using built-in functions to create ndArrays, such as arange(), ones(), zeros(), etc.

In [2]:
import numpy as np

x = np.array([1, 2, 3])

In [3]:
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
x.dtype

dtype('int64')

In [5]:
x.shape

(3,)

In [6]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
Y.shape

(3, 3)

In [8]:
Y.size

9

In [9]:
x = np.array(["Hello", "World"])
print(x)

['Hello' 'World']


In [10]:
print("shape: ", x.shape)
print("type: ", type(x))
print("dtype: ", x.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


### Upcasting
NumPy makes sure that all the elements in a NumPy array are of the same data type. If the elements are of different data types, NumPy will upcast if possible. The order of upcasting is: bool -> int -> float -> str.

In [11]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [12]:
x = np.array([1.5, 2.2, 3.2], dtype=np.int64)
print(x, x.dtype)

[1 2 3] int64


In [13]:
x = np.array([1, 2, 3])
np.save('my_array', x)

In [14]:
y = np.load('my_array.npy')
print(y)

[1 2 3]


#### Creating ndArrays from built-in functions

In [18]:
X = np.zeros((3, 4), dtype=np.int32)
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [20]:
X = np.ones((3, 4))
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
X = np.full((3, 4), 5)
print(X)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Identity Matrix

In [29]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Diagonal Matrix

In [32]:
X = np.diag([10, 1, 3, 5])
print(X)

[[10  0  0  0]
 [ 0  1  0  0]
 [ 0  0  3  0]
 [ 0  0  0  5]]


In [35]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
x = np.arange(5, 10)
print(x)

[5 6 7 8 9]


In [39]:
x = np.arange(2, 12, 2)
print(x)

[ 2  4  6  8 10]


In [46]:
x = np.linspace(0, 20, 10, endpoint=False)
print(x)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [48]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [51]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [53]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [54]:
Y = np.arange(20).reshape(4, 5)
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [56]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [58]:
X = np.random.random((5, 3))
print(X)

[[0.50160312 0.5560983  0.34185583]
 [0.7545825  0.97681578 0.2768332 ]
 [0.00455033 0.94909559 0.46137681]
 [0.03277143 0.05856955 0.59647445]
 [0.49399897 0.98253688 0.1653453 ]]


In [60]:
X = np.random.randint(2, 10, (3, 3))
print(X)

[[4 8 7]
 [7 8 7]
 [5 4 6]]


In [62]:
X = np.random.normal(0, 0.3, (100, 100))
print(X)

[[-0.07806183  0.20611142  0.27733855 ...  0.15234755  0.01763315
   0.07830221]
 [ 0.12674517  0.28397315  0.17920669 ... -0.30251805  0.01935122
  -0.77635095]
 [ 0.18535828 -0.03147611 -0.09720029 ...  0.03528646 -0.35738241
  -0.01332369]
 ...
 [-0.38848035  0.34745868  0.3975081  ... -0.12860521  0.49248118
   0.32890943]
 [-0.06780213 -0.00612783 -0.22220213 ... -0.19067118 -0.07614852
  -0.15258948]
 [-0.42036602  0.42090732  0.29226171 ...  0.12910429  0.00422766
   0.0456572 ]]


In [63]:
print("Mean: ", X.mean())
print("Std: ", X.std())
print("Max: ", X.max())
print("Min: ", X.min())
print("# positive: ", (X > 0).sum())
print("# negative: ", (X < 0).sum())

Mean:  0.004992061755576502
Std:  0.2995345122965457
Max:  1.199364367422568
Min:  -1.0876668452896103
# positive:  5042
# negative:  4958
