## Creating NumPy ndArrays
Mainly there are two ways to create NumPy ndArrays:
1. Using array() function to create ndArrays from Python lists, tuples, or any other iterable object.
2. Using built-in functions to create ndArrays, such as arange(), ones(), zeros(), etc.

In [2]:
import numpy as np

x = np.array([1, 2, 3])

In [4]:
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
x.dtype

dtype('int64')

In [8]:
x.shape

(3,)

In [10]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
Y.shape

(3, 3)

In [14]:
Y.size

9

In [16]:
x = np.array(["Hello", "World"])
print(x)

In [18]:
print("shape: ", x.shape)
print("type: ", type(x))
print("dtype: ", x.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


### Upcasting
NumPy makes sure that all the elements in a NumPy array are of the same data type. If the elements are of different data types, NumPy will upcast if possible. The order of upcasting is: bool -> int -> float -> str.

In [20]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [22]:
x = np.array([1.5, 2.2, 3.2], dtype=np.int64)
print(x, x.dtype)

[1 2 3] int64


In [24]:
x = np.array([1, 2, 3])
np.save('my_array', x)

In [25]:
y = np.load('my_array.npy')
print(y)

[1 2 3]
