## Creating NumPy ndArrays
Mainly there are two ways to create NumPy ndArrays:
1. Using array() function to create ndArrays from Python lists, tuples, or any other iterable object.
2. Using built-in functions to create ndArrays, such as arange(), ones(), zeros(), etc.

In [139]:
import numpy as np

x = np.array([1, 2, 3])

In [140]:
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [141]:
x.dtype

dtype('int64')

In [142]:
x.shape

(3,)

In [143]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [144]:
Y.shape

(3, 3)

In [145]:
Y.size

9

In [146]:
x = np.array(["Hello", "World"])
print(x)

['Hello' 'World']


In [147]:
print("shape: ", x.shape)
print("type: ", type(x))
print("dtype: ", x.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


### Upcasting
NumPy makes sure that all the elements in a NumPy array are of the same data type. If the elements are of different data types, NumPy will upcast if possible. The order of upcasting is: bool -> int -> float -> str.

In [148]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [149]:
x = np.array([1.5, 2.2, 3.2], dtype=np.int64)
print(x, x.dtype)

[1 2 3] int64


In [150]:
x = np.array([1, 2, 3])
np.save('my_array', x)

In [151]:
y = np.load('my_array.npy')
print(y)

[1 2 3]


#### Creating ndArrays from built-in functions

In [152]:
X = np.zeros((3, 4), dtype=np.int32)
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [153]:
X = np.ones((3, 4))
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [154]:
X = np.full((3, 4), 5)
print(X)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Identity Matrix

In [155]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Diagonal Matrix

In [156]:
X = np.diag([10, 1, 3, 5])
print(X)

[[10  0  0  0]
 [ 0  1  0  0]
 [ 0  0  3  0]
 [ 0  0  0  5]]


In [157]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [158]:
x = np.arange(5, 10)
print(x)

[5 6 7 8 9]


In [159]:
x = np.arange(2, 12, 2)
print(x)

[ 2  4  6  8 10]


In [160]:
x = np.linspace(0, 20, 10, endpoint=False)
print(x)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [161]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [162]:
x = np.reshape(x, (4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [163]:
x = np.reshape(x, (10, 2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [164]:
Y = np.arange(20).reshape(4, 5)
print(Y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [165]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [166]:
X = np.random.random((5, 3))
print(X)

[[0.94004352 0.51647603 0.70699152]
 [0.27696827 0.40683984 0.99086998]
 [0.79898405 0.61487055 0.76722837]
 [0.46132201 0.84230333 0.88858101]
 [0.02668331 0.0198129  0.76822802]]


In [167]:
X = np.random.randint(2, 10, (3, 3))
print(X)

[[7 7 4]
 [9 3 8]
 [4 2 6]]


In [168]:
X = np.random.normal(0, 0.3, (100, 100))
print(X)

[[ 0.34993445  0.0681384  -0.15651486 ...  0.33142623 -0.16738539
  -0.07303317]
 [-0.00666284 -0.36683576 -0.15267889 ...  0.26928676 -0.15022818
  -0.09876387]
 [-0.00155876 -0.37036585  0.40074461 ... -0.38802947  0.26406419
  -0.34460087]
 ...
 [-0.18465105  0.19481244  0.09013287 ...  0.40860458 -0.05941832
  -0.34846933]
 [ 0.45375749  0.00541158  0.63855063 ... -0.17498478 -0.02128779
   0.08067538]
 [ 0.04554159 -0.16685338 -0.07477001 ...  0.23881735 -0.2007582
   0.40724025]]


In [169]:
print("Mean: ", X.mean())
print("Std: ", X.std())
print("Max: ", X.max())
print("Min: ", X.min())
print("# positive: ", (X > 0).sum())
print("# negative: ", (X < 0).sum())

Mean:  0.00664453451035468
Std:  0.30030959282338127
Max:  1.0347128322085004
Min:  -1.069553541065856
# positive:  5113
# negative:  4887


## Accessing, Deleting and Inserting Elements Into ndArrays

In [170]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [171]:
print("1st element: ", x[0])
print("2nd element: ", x[1])
print("5th element: ", x[4])

1st element:  1
2nd element:  2
5th element:  5


In [172]:
print("1st element: ", x[-5])
print("2nd element: ", x[-4])
print("5th element: ", x[-1])

1st element:  1
2nd element:  2
5th element:  5


In [173]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [174]:
X = np.arange(1, 10).reshape(3, 3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [175]:
print("Element (0, 0): ", X[0, 0])
print("Element (0, 1): ", X[0, 1])
print("Element (2, 2): ", X[2, 2])

Element (0, 0):  1
Element (0, 1):  2
Element (2, 2):  9


In [176]:
X[0, 0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [177]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0, 4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [178]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

W = np.delete(Y, 0, axis=0)
print('\n',W)

V = np.delete(Y, [0, 2], axis=1)
print('\n',V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [179]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [180]:
x = np.append(x, [7, 8])
print(x)

[1 2 3 4 5 6 7 8]


In [181]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [182]:
W = np.append(Y, [[10, 11, 12]], axis=0)
print('\n',W)


 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [183]:
V = np.append(Y, [[10], [11], [12]], axis=1)
print('\n',V)


 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [184]:
x = np.array([1, 2, 5, 6, 7])
print(x)

[1 2 5 6 7]


In [185]:
x = np.insert(x, 2, [3, 4])
print(x)

[1 2 3 4 5 6 7]


In [186]:
Y = np.array([[1, 2, 3], [7, 8, 9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [187]:
W = np.insert(Y, 1, [4, 5, 6], axis=0)
print('\n',W)


 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [188]:
V = np.insert(Y, 1, 5, axis=1)
print('\n',V)


 [[1 5 2 3]
 [7 5 8 9]]


In [189]:
x = np.array([1, 2])
print(x)

[1 2]


In [190]:
Y = np.array([[3, 4], [5, 6]])
print(Y)

[[3 4]
 [5 6]]


In [191]:
z = np.vstack((x, Y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [192]:
w = np.hstack((Y, x.reshape(2, 1)))
print(w)

[[3 4 1]
 [5 6 2]]


## Slicing ndArrays

In [193]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [194]:
z = X[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [195]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [196]:
z = X[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [197]:
z = X[:, 2]
print(z)

[ 3  8 13 18]


In [198]:
z = X[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [199]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [200]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [201]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [202]:
print(X)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [203]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [204]:
z = np.copy(X[1:, 2:])
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [205]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [206]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [207]:
z = np.diag(X)
print(z)

[ 1  7 13 19]


In [208]:
z = np.diag(X, k=1)
print(z)

[ 2  8 14 20]


In [209]:
z = np.diag(X, k=-1)
print(z)

[ 6 12 18]


In [210]:
X = np.array([[1, 3, 5], [1, 5, 2], [3, 4, 2]])
z = np.unique(X)
print(z)

[1 2 3 4 5]


## Boolean indexing, Set Operations, and Sorting

## 

In [211]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [212]:
print(X[X > 10])


[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [213]:
print(X[X <= 7])


[0 1 2 3 4 5 6 7]


In [214]:
print(X[(X > 10) & (X < 17)])

[11 12 13 14 15 16]


In [215]:
X[(X > 10) & (X < 17)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [216]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [218]:
x = np.random.randint(1, 11, size=(10,))
print(x)

[ 1  4  5  5  1 10  8  3  1  3]


In [220]:
print(np.sort(x))
print(x)

[ 1  1  1  3  3  4  5  5  8 10]
[ 1  4  5  5  1 10  8  3  1  3]


In [221]:
x.sort()
print(x)

[ 1  1  1  3  3  4  5  5  8 10]


In [222]:
X = np.random.randint(1, 11, size=(5, 5))
print(X)

[[ 7  2  1 10  8]
 [ 9  6  4  5 10]
 [ 5  7  4 10  2]
 [ 4  8  6  3  6]
 [ 5 10  6  7  3]]


In [223]:
print(np.sort(X, axis=0))

[[ 4  2  1  3  2]
 [ 5  6  4  5  3]
 [ 5  7  4  7  6]
 [ 7  8  6 10  8]
 [ 9 10  6 10 10]]


In [224]:
print(np.sort(X, axis=1))

[[ 1  2  7  8 10]
 [ 4  5  6  9 10]
 [ 2  4  5  7 10]
 [ 3  4  6  6  8]
 [ 3  5  6  7 10]]
